config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :feedbacks
  resources :members
  resources :events
  resources :categories
  resources :owner_photos
  resources :owners
  root to: 'home#index'
  devise_for :users
  resources :users
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  geocoded_by :full_address, :latitude  => :lat, :longitude => :lon # ActiveRecord

  validates_presence_of :city, :address, :province
  after_validation :geocode

  MUNICIPALLIES=(1..19).to_a
  LEVELS=%w(Gold Silver Bronze)

  def full_address
    [address, city, province, "Italy"].compact.join(', ')
  end

  def to_label
    "#{nome}"
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:nome, :note, :address, :city, :cap, :municipality, :province, :lat, :lon, :level, :signed_since)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.haml
= simple_form_for(@owner) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome
    = f.input :address
    = f.input :city
    = f.input :province
    = f.input :cap
    = f.input :municipality, as: :select, collection: Owner::MUNICIPALLIES
    = f.input :level, as: :select, collection: Owner::LEVELS
    = f.input :lat
    = f.input :lon
    = f.input :signed_since
    = f.input :note

  .form-actions
    = f.button :submit

app/views/owners/edit.html.haml
%h1 Editing owner

= render 'form'

= link_to 'Show', @owner
\|
= link_to 'Back', owners_path

app/views/owners/index.html.haml
%h1 Listing owners

%table
  %thead
    %tr
      %th Nome
      %th Note
      %th Address
      %th Cap
      %th Municipality
      %th Province
      %th Lat
      %th Lon
      %th Level
      %th Signed since
      %th
      %th
      %th

  %tbody
    - @owners.each do |owner|
      %tr
        %td= owner.nome
        %td= owner.note
        %td= owner.address
        %td= owner.cap
        %td= owner.municipality
        %td= owner.province
        %td= owner.lat
        %td= owner.lon
        %td= owner.level
        %td= owner.signed_since
        %td= link_to 'Show', owner
        %td= link_to 'Edit', edit_owner_path(owner)
        %td= link_to 'Destroy', owner, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Owner', new_owner_path

app/views/owners/new.html.haml
%h1 New owner

= render 'form'

= link_to 'Back', owners_path

app/views/owners/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @owner.nome
%p
  %b Note:
  = @owner.note
%p
  %b Address:
  = @owner.address
%p
  %b Cap:
  = @owner.cap
%p
  %b Municipality:
  = @owner.municipality
%p
  %b Province:
  = @owner.province
%p
  %b Lat:
  = @owner.lat
%p
  %b Lon:
  = @owner.lon
%p
  %b Level:
  = @owner.level
%p
  %b Signed since:
  = @owner.signed_since

= link_to 'Edit', edit_owner_path(@owner)
\|
= link_to 'Back', owners_path