config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :feedbacks
  resources :members
  resources :events
  resources :categories
  resources :owner_photos
  resources :owners
  root to: 'home#index'
  devise_for :users
  resources :users
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:event_id, :user_id, :vote, :comment, :is_anonymous)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.haml
= simple_form_for(@feedback) do |f|
  = f.error_notification

  .form-inputs
    = f.input :event_id
    = f.input :user_id
    = f.input :vote
    = f.input :comment
    = f.input :is_anonymous

  .form-actions
    = f.button :submit

app/views/feedbacks/edit.html.haml
%h1 Editing feedback

= render 'form'

= link_to 'Show', @feedback
\|
= link_to 'Back', feedbacks_path

app/views/feedbacks/index.html.haml
%h1 Listing feedbacks

%table
  %thead
    %tr
      %th Event
      %th User
      %th Vote
      %th Comment
      %th Is anonymous
      %th
      %th
      %th

  %tbody
    - @feedbacks.each do |feedback|
      %tr
        %td= feedback.event_id
        %td= feedback.user_id
        %td= feedback.vote
        %td= feedback.comment
        %td= feedback.is_anonymous
        %td= link_to 'Show', feedback
        %td= link_to 'Edit', edit_feedback_path(feedback)
        %td= link_to 'Destroy', feedback, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Feedback', new_feedback_path

app/views/feedbacks/new.html.haml
%h1 New feedback

= render 'form'

= link_to 'Back', feedbacks_path

app/views/feedbacks/show.html.haml
%p#notice= notice

%p
  %b Event:
  = @feedback.event_id
%p
  %b User:
  = @feedback.user_id
%p
  %b Vote:
  = @feedback.vote
%p
  %b Comment:
  = @feedback.comment
%p
  %b Is anonymous:
  = @feedback.is_anonymous

= link_to 'Edit', edit_feedback_path(@feedback)
\|
= link_to 'Back', feedbacks_path